## pyimpsort.el
*Sort python imports. -*- lexical-binding: t -*-*

---
[![Travis build status](https://travis-ci.org/emacs-pe/pyimpsort.el.png?branch=master)](https://travis-ci.org/emacs-pe/pyimpsort.el)

`pyimpsort.el` sort the python imports of a file.
Currently uses [pyimpsort.py](pyimpsort.py) to process the way to sort python
imports.

### Setup

Add the following snippet to your `init.el`:

    (require 'pyimpsort)
    (eval-after-load 'python
      '(define-key python-mode-map "\C-c\C-u" #'pyimpsort-buffer))

### Troubleshooting

+ **Doesn't sort correcly third party libraries**

  `pyimpsort.el` tries to identify the third party libraries if are installed
  in in the PYTHONPATH, if a package is not installed it is assumed that
  belongs to the application.
  `pyimpsort.el` also tries to identify if a python virtualenv
  is activated.

### Related projects

+ [isort][] ([emacs integration](https://github.com/paetzke/py-isort.el))

[isort]: https://github.com/timothycrosley/isort

### Function Documentation


#### `(pyimpsort-region BEGIN END)`

Sort python imports from region BEGIN to END points.

#### `(pyimpsort-buffer)`

Sort python imports from current buffer.

-----
<div style="padding-top:15px;color: #d0d0d0;">
Markdown README file generated by
<a href="https://github.com/mgalgs/make-readme-markdown">make-readme-markdown.el</a>
</div>
